-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 19/01/2025 às 22:17
-- Versão do servidor: 10.4.32-MariaDB
-- Versão do PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `clubeliterario`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `leitura`
--

CREATE TABLE `leitura` (
  `idLivro` int(11) NOT NULL,
  `idUsuario` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `leitura`
--

INSERT INTO `leitura` (`idLivro`, `idUsuario`) VALUES
(3, 3),
(4, 2),
(6, 3);

-- --------------------------------------------------------

--
-- Estrutura para tabela `livro`
--

CREATE TABLE `livro` (
  `id` int(11) NOT NULL,
  `nome` varchar(500) NOT NULL,
  `genero` varchar(150) NOT NULL,
  `autor` varchar(500) NOT NULL,
  `ano` int(11) NOT NULL,
  `numPaginas` int(11) NOT NULL,
  `ISBN` varchar(100) NOT NULL,
  `nacionalidade` varchar(50) NOT NULL,
  `sinopse` varchar(10000) NOT NULL,
  `qtdvisualizacoes` int(11) NOT NULL,
  `capa_path` varchar(200) NOT NULL,
  `livro_path` varchar(200) NOT NULL,
  `data_upload` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `livro`
--

INSERT INTO `livro` (`id`, `nome`, `genero`, `autor`, `ano`, `numPaginas`, `ISBN`, `nacionalidade`, `sinopse`, `qtdvisualizacoes`, `capa_path`, `livro_path`, `data_upload`) VALUES
(3, 'Memórias póstumas de Brás Cubas', 'Romance', 'Machado de Assis', 1881, 140, '000-000-000-008', 'Nacional', 'Após ter morrido, em pleno ano de 1869, Brás Cubas decide por narrar sua história e revisitar os fatos mais importantes de sua vida, a fim de se distrair na eternidade. A partir de então ele relembra de amigos como Quincas Borba, de sua displicente formação acadêmica em Portugal, dos amores de sua vida e ainda do privilégio que teve de nunca ter precisado trabalhar em sua vida.', 0, 'https://m.media-amazon.com/images/I/71OL9RU2tJL._SL1360_.jpg', 'upload/livros/678d19e2b7d3cpdf', '2025-01-19 12:27:30'),
(4, 'A mão e a luva', 'Romance', 'Machado de Assis', 1874, 68, '000-000-000-09', 'Nacional', 'Segundo romance escrito por Machado de Assis, publicado em 1874, embora não tenha toda grandiosidade das obras mais famosas, merece posição de grande destaque. A história se desenrola de maneira agradável, interessante e até cômica. A crítica à sociedade e seus interesses, ainda mais fortes à época do que hoje, dão a tônica deste livro. Apesar de a obra ser enquadrada na fase romântica do autor, em vez dos recursos clássicos do Romantismo enredos rocambolescos, plenos de coincidências, reviravoltas, surpresas e suspenses Machado prefere um texto contido, minimalista em termos de trama, de análise psicológica, e com uma elegância estilística que foi se aperfeiçoando até atingir seus píncaros na chamada fase realista. Apenas nas últimas linhas deslinda-se o título, escolhido de forma rigorosa pelo autor e que sintetiza o intuito da obra.', 0, 'https://m.media-amazon.com/images/I/613D-uzZ8AL._SL1360_.jpg', 'upload/livros/678d1a2c1406epdf', '2025-01-19 12:28:44'),
(5, 'Ressurreição', 'Romance', 'Machado de Assis', 1872, 80, '000-000-000-010', 'Nacional', 'Ressurreição é o primeiro romance de Machado de Assis, e publicado em 1872. A história começa com Félix, homem que tem um relacionamento com Cecília por um período de seis meses (segundo ele próprio, uma paixão não poderia passar de um semestre). Abandona a namorada. Viana, seu amigo, apresenta sua irmã Lívia pela segunda vez (a primeira tinha sido rápida, menos de 5 minutos), uma bela mulher, viúva há dois anos. Eles começam a se relacionar como amigos, enquanto ele, o Doutor Félix, médico, se enamorara pela jovem viúva. O tempo foi passando, e ele cada vez mais apaixonado por ela. Félix finalmente declara-se, porém de forma indireta. Começam a viver um amor secreto, escondido às vistas da sociedade. Porém, vários conflitos passam a ocorrer devido ao que aconteceu com Lívia, mas o romance começa a ter vários obstáculos então Félix pede a viúva em casamento ela aceita mas a viúva então descobre que Raquel também e apaixonada por Félix mas a inocência da menina a faz desistir do amar Félix pelo bem do coração da viúva.', 0, 'https://m.media-amazon.com/images/I/61DouJElapL._SL1335_.jpg', 'upload/livros/678d1a7c2efd6pdf', '2025-01-19 12:30:04'),
(6, 'Helena', 'Romance', 'Machado de Assis', 1876, 139, '000-000-000-011', 'Nacional', 'Helena, obra de Machado de Assis, narra a história de Helena, que, considerada uma filha abastarda, é reconhecida e acolhida pela família de seu pai, quando este falece. O livro inicia seu enredo exatamente nesse momento, quando o Conselheiro Vale, pai de Helena, tem sua morte ocasionada por apoplexia, após sua sesta. Deixa para trás seu filho Estácio, sua irmã D. Úrsula, seu amigo Dr. Camargo, e sua filha que estará num internato, chamada Helena.', 0, 'https://m.media-amazon.com/images/I/61KDbIA7t6L._SL1360_.jpg', 'upload/livros/678d1ad16c7f2pdf', '2025-01-19 12:31:29'),
(7, 'Iaiá Garcia', 'Romance', 'Machado de Assis', 1878, 107, '000-000-000-012', 'Nacional', 'Luis Garcia era um homem reservado e que vivia exclusivamente por sua filha, Lina. Viúvo, vivia em uma casa mais afastada que se enchia de alegria quando Lina, ou melhor, Iaiá Garcia, chegava da escola. Na casa ainda havia um negro que era todo dedicado ao senhor e sua filha. No círculo pequeno de amizades de Luis estava a Sra. Valéria, também viúva. Esta tinha um filho, Jorge. E foi por ele que Valéria chamou Luis à sua casa. Acontecia que ela desejava mandar o filho à guerra do Paraguai e queria que Luis a ajudasse a fazer a cabeça do jovem. Justificava esse desejo afirmando que era seu dever como cidadão e também em referência às glórias e méritos que tais conflitos geram aos vencedores, não acreditando na morte do filho. Porém sua verdadeira razão era fazê-lo  esquecer uma grande paixão.', 0, 'https://m.media-amazon.com/images/I/71KjaiJzLAL._SL1354_.jpg', 'upload/livros/678d4f208adb9pdf', '2025-01-19 16:14:40'),
(8, 'Casa Velha', 'Romance', 'Machado de Assis', 1886, 52, '000-000-000-013', 'Nacional', 'Entremeada por temas dos primeiros romances de Machado, a obra trata principalmente da ascensão social por meio do casamento. Narrado por um padre que investiga documentos sobre o Primeiro Reinado na residência de um falecido ministro, o livro se debruça sobre a fortuita paixão entre o herdeiro Félix e a agregada da casa, Lalau.', 0, 'https://m.media-amazon.com/images/I/81mZwQB6JBL._SL1500_.jpg', 'upload/livros/678d4f662b341pdf', '2025-01-19 16:15:50'),
(9, 'Quincas Borba', 'Romance', 'Machado de Assis', 1891, 158, '000-000-000-014', 'Nacional', 'Publicado em 1891, o romance conta a vida de Rubião, um pacato professor que se torna rico da noite para o dia ao receber uma herança deixada pelo filósofo Quincas Borba, criador de uma filosofia chamada Humanitismo. Rubião passa a viver no fausto da Corte do Rio de Janeiro, num ambiente a que não estava acostumado e que muito o deslumbra. Torna-se amigo de um casal, Palha e Sofia, em torno dos quais e do próprio Rubião gira todo o enredo do romance. Há também um cachorro, o Quincas Borba, que herdou o nome do filósofo, que fora seu dono, antes que ele passasse a pertencer a Rubião.', 0, 'https://m.media-amazon.com/images/I/61Kt3d+mhuL._SL1360_.jpg', 'upload/livros/678d4faec16ffpdf', '2025-01-19 16:17:02'),
(10, 'Dom Casmurro', 'Romance', 'Machado de Assis', 1899, 128, '000-000-000-015', 'Nacional', '\"Dom Casmurro\" conta a história de Bento Santiago (Bentinho), apelidado de Dom Casmurro por ser calado e introvertido. Na adolescência, apaixona-se por Capítu, abandonando o seminário e, com ele, os desígnios traçados por sua mãe, Dona Glória, para que se tornasse padre.', 0, 'https://m.media-amazon.com/images/I/61Z2bMhGicL._SL1360_.jpg', 'upload/livros/678d4fed5fdc7pdf', '2025-01-19 16:18:05'),
(11, 'Esaú e Jacó', 'Romance', 'Machado de Assis', 1904, 135, '000-000-000-016', 'Nacional', 'Dois jovens bem-nascidos, os gêmeos Pedro e Paulo, digladiam-se em intermináveis conflitos e reconciliações desde o útero da mãe até o começo da idade adulta. Os irmãos lutam pelo amor da jovem Flora Batista, cujo enredo é narrado em terceira pessoa pelo conselheiro Aires - alter-ego de Machado de Assis, que usa o personagem para as suas reflexões autorais. O narrador-personagem compartilha com o leitor suas indagações sobre a arte do romance e, por isso, o crítico e professor Hélio Guimarães, que assina a introdução e as notas do volume, considera essa obra uma verdadeira “teoria da composição ficcional”. Ambientado no Rio de Janeiro durante os anos finais do Império e o início da República, o livro ecoa diversos acontecimentos da história do Brasil - incluindo a Abolição, a Proclamação da República e as revoltas contra o governo Floriano Peixoto -, além de passagens da Bíblia, da Divina comédia e do Fausto de Goethe.', 0, 'https://m.media-amazon.com/images/I/81Oj0Etf1uL._SL1500_.jpg', 'upload/livros/678d502d0bff4pdf', '2025-01-19 16:19:09'),
(12, 'Memorial de Aires', 'Romance', 'Machado de Assis', 1908, 116, '000-000-000-017', 'Nacional', 'Por ser o último romance de Machado de Assis, Memorial de Aires tem muitas características particulares e interessantes. A obra é a única do autor que tem um formato de memórias registradas em um diário. Os relatos do Conselheiro Aires percorrem os anos de 1888 e 1889, ou seja, anos em que ocorreram dois fatos importantes na história do país: a abolição da escravatura e a proclamação da República. No enredo há temas substanciais como a morte, a solidão na velhice, e, como característica fundamental de Machado, a descrição das fraquezas humanas. Para muitos, o livro tem características autobiográficas, mas são apenas cogitações, o fato é que esta obra é uma síntese bem acabada das muitas histórias legadas pelo autor à nossa literatura.', 0, 'https://m.media-amazon.com/images/I/61R-l9vG27S._SL1500_.jpg', 'upload/livros/678d508136bc5pdf', '2025-01-19 16:20:33'),
(13, 'Harry Potter e a Pedra Filosofal', 'Fantasia', 'J.K Rowling', 1997, 274, '000-000-000-001', 'Internacional', 'Harry Potter e a pedra filosofal é o primeiro dos sete livros da série de fantasia Harry Potter, escrita por J. K. Rowling. O livro conta a história de Harry Potter, um órfão criado pelos tios que descobre, em seu décimo primeiro aniversário, que é um bruxo.', 0, 'https://m.media-amazon.com/images/I/81ibfYk4qmL._SL1500_.jpg', 'upload/livros/678d50df7ff42pdf', '2025-01-19 16:22:07'),
(14, 'Harry Potter e a Câmara Secreta', 'Fantasia', 'J.K Rowling', 1998, 186, '000-000-000-002', 'Internacional', 'Após as sofríveis férias na casa dos tios, Harry Potter se prepara para voltar a Hogwarts e começar seu segundo ano na escola de bruxos. Na véspera do início das aulas, a estranha criatura Dobby aparece em seu quarto e o avisa de que voltar é um erro e que algo muito ruim pode acontecer se Harry insistir em continuar os estudos de bruxaria. O garoto, no entanto, está disposto a correr o risco e se livrar do lar problemático.', 0, 'https://m.media-amazon.com/images/I/81jbivNEVML._SL1500_.jpg', 'upload/livros/678d51161a2b9pdf', '2025-01-19 16:23:02'),
(15, 'Harry Potter e o prisioneiro de azkaban', 'Fantasia', 'J.K Rowling', 1999, 394, '000-000-000-003', 'Internacional', 'É o início do terceiro ano na escola de bruxaria Hogwarts. Harry, Ron e Hermione têm muito o que aprender. Mas uma ameaça ronda a escola e ela se chama Sirius Black. Após doze anos encarcerado na prisão de Azkaban, ele consegue escapar e volta para vingar seu mestre, Lord Voldemort. Para piorar, os Dementores, guardas supostamente enviados  para proteger Hogwarts e seguir os passos de Black, parecem ser ameaças ainda mais perigosas.', 0, 'https://m.media-amazon.com/images/I/81u+ljPVifL._SL1500_.jpg', 'upload/livros/678d515f54c68pdf', '2025-01-19 16:24:15'),
(16, 'Harry Potter e o cálice de fogo', 'Fantasia', 'J.K Rowling', 2000, 586, '000-000-000-004', 'Internacional', 'Harry retorna para seu quarto ano na Escola de Magia e Bruxaria de Hogwarts, junto com os seus amigos Ron e Hermione. Desta vez, acontece um torneio entre as três maiores escola de magia, com um participante selecionado de cada escola, pelo Cálice de Fogo. O nome de Harry aparece, mesmo não tendo se inscrito, e ele precisa competir.', 0, 'https://m.media-amazon.com/images/I/81nTLN-kz7L._SL1500_.jpg', 'upload/livros/678d51e94e3e7pdf', '2025-01-19 16:26:33'),
(17, 'Harry Potter e a ordem da fênix', 'Fantasia', 'J.K Rowling', 2003, 770, '000-000-000-005', 'Internacional', 'Após um verão desastroso, Harry volta para o seu quinto ano em Hogwarts, um dos mais difíceis que terá de encarar. Pouquíssimos alunos e pais acreditam nele ou em Dumbledore sobre a volta de Voldemort, e uma série interminável de artigos circula dizendo que eles estão completamente malucos. Ainda por cima, Dolores Umbridge, a nova professora de Defesa Contra as Artes das Trevas, prova ser a pessoa mais repugnante que Harry já conheceu.', 0, 'https://m.media-amazon.com/images/I/81d6ESyPZwL._SL1500_.jpg', 'upload/livros/678d52e193819pdf', '2025-01-19 16:30:41'),
(18, 'Harry Potter e o enigma do príncipe', 'Fantasia', 'J.K. Rowling', 2005, 507, '000-000-000-006', 'Internacional', 'No sexto ano de Harry em Hogwarts, Lord Voldemort e seus Comensais da Morte estão criando o terror nos mundos bruxo e trouxa. Dumbledore convence seu velho amigo Horácio Slughorn para retornar a Hogwarts como professor de poções após Harry encontrar um estranho livro escolar. Draco Malfoy se esforça para realizar uma ação destinada por Voldemort, enquanto Dumbledore e Harry secretamente trabalham juntos a fim de descobrir o método para destruir o Lorde das Trevas uma vez por todas.', 0, 'https://m.media-amazon.com/images/I/81yFIh1yoZL._SL1500_.jpg', 'upload/livros/678d532e9df09pdf', '2025-01-19 16:31:58'),
(19, 'Harry Potter e as relíquias da morte', 'Fantasia', 'J.K Rowling', 2007, 633, '000-000-000-007', 'Internacional', 'Harry Potter está prestes a fazer 17 anos, mas, ao contrário das outras vezes, não irá para Hogwarts após seu aniversário. Agora, escoltado por uma verdadeira brigada de bruxos, ele precisa fugir, antes que Voldemort o encontre.Em Harry Potter e as Relíquias da Morte, o encontro inevitável com Lorde Voldemort não pode mais ser adiado. Harry, no entanto, precisa ganhar tempo para encontrar as Horcruxes que ainda estão faltando. E, pelo caminho, descobrir o que são afinal as Relíquias da Morte e como ele pode usá-las contra o Lorde das Trevas. Seguindo as poucas pistas deixadas por Dumbledore, Harry conta apenas com a ajuda dos leais amigos Rony e Hermione.Juntos, eles percorrem lugares nunca visitados, descobrem histórias nebulosas sobre pessoas queridas e acabam por desvendar mistérios que os incomodavam há muito tempo.', 0, 'https://m.media-amazon.com/images/I/81rvO7xcJOL._SL1500_.jpg', 'upload/livros/678d536e4f68fpdf', '2025-01-19 16:33:02'),
(20, 'O misterioso caso de Styles', 'Mistério', 'Agatha Christie', 1920, 99, '000-000-000-018', 'Internacional', 'Emily Inglethorp, madrasta de John e Laurence Cavendish, herdou a propriedade de seu marido e tem todo o controle sobre patrimônio da família. Seu segundo marido é Alfred Inglethorp, vinte anos mais novo, cujo passado é nebuloso, o que causa enorme apreensão nos filhos de mrs. Emily e nos demais moradores de Styles.', 0, 'https://http2.mlstatic.com/D_NQ_NP_2X_995242-MLU77442192803_072024-F.webp', 'upload/livros/678d56339ec4bpdf', '2025-01-19 16:44:51'),
(21, 'O adversário secreto', 'Mistério', 'Agatha Christie', 1922, 210, '000-000-000-019', 'Internacional', 'Primeira Guerra Mundial acabou, e a Inglaterra enfrenta um período de poucos empregos. Tommy Beresford e Prudence “Tuppence” Cowley, dois jovens que se conheciam de antes da guerra, se encontram por acaso em Londres e descobrem que têm em comum energia de sobra, pouco dinheiro e nenhuma oportunidade de trabalho.', 0, 'https://m.media-amazon.com/images/I/A1AyJjCssnL._SL1500_.jpg', 'upload/livros/678d567583917pdf', '2025-01-19 16:45:57'),
(22, 'Os cinco porquinhos', 'Mistério', 'Agatha Christie', 1942, 206, '000-000-000-020', 'Internacional', 'Caroline Crale foi condenada à prisão perpétua e submetida a trabalhos forçados pelo assassinato do marido, o famoso pintor Amyas Crale. Mas, antes de morrer na prisão, enviara à filha, então criança, uma carta afirmando sua inocência. Tantos anos depois, não há mais evidências a serem colhidas.', 0, 'https://m.media-amazon.com/images/I/91VpEyvWxjL._SL1500_.jpg', 'upload/livros/678d56b2b8fe7pdf', '2025-01-19 16:46:58'),
(23, 'Os três ratos cegos e outros contos', 'Mistério', 'Agatha Christie', 1950, 146, '000-000-000-021', 'Internacional', 'Uma nevasca prende um grupo de desconhecidos no isolado Solar Monkswell junto com um assassino psicótico; Hercule Poirot tenta desesperadamente salvar uma criança sequestrada; Miss Marple tenta proteger os herdeiros de um homem recém-falecido de um desastre iminente; e Mr. Harley Quin persegue um assassino ardiloso.Unindo um de seus contos mais famosos com mistérios dos detetives mais queridos da autora, Três ratos cegos e outros contos traz uma Agatha Christie em ápice inventivo.', 0, 'https://m.media-amazon.com/images/I/71pz1UaMlEL._SL1500_.jpg', 'upload/livros/678d5714f3e4bpdf', '2025-01-19 16:48:37'),
(24, 'O assassinato no expresso oriente', 'Mistério', 'Agatha Christie', 1934, 143, '000-000-000-022', 'Internacional', 'O detetive belga, então, embarca às pressas no Expresso do Oriente, inesperadamente lotado para aquela época do ano. O trem expresso, porém, é detido a meio caminho da Iugoslávia por uma forte nevasca, e um passageiro com muitos inimigos é brutalmente assassinado durante a madrugada.', 0, 'https://m.media-amazon.com/images/I/81Zp6MFxIDL._SL1500_.jpg', 'upload/livros/678d575eea346pdf', '2025-01-19 16:49:50'),
(25, 'Morte no Nilo', 'Mistério', 'Agatha Christie', 1937, 157, '000-000-000-023', 'Internacional', 'A tranquilidade de um cruzeiro de luxo pelo Nilo chega ao fim quando o corpo de Linnet Doyle, uma bela e jovem milionária, é descoberto em sua cabine. Porém, para azar do autor do crime, o brilhante detetive Hercule Poirot está a bordo.', 0, 'https://m.media-amazon.com/images/I/71Jt2eJxI6L._SL1500_.jpg', 'upload/livros/678d579bdf8c3pdf', '2025-01-19 16:50:51'),
(26, 'A noite das bruxas', 'Mistério', 'Agatha Christie', 1969, 216, '000-000-000-024', 'Internacional', 'Ariadne Oliver, Joyce, uma adolescente com o costume de mentir para chamar a atenção, revela já ter testemunhado um assassinato. Ninguém acredita nela, mas, poucas horas depois, seu corpo é encontrado afogado próximo a uma bacia cheia de maçãs.', 0, 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1608902257l/56408407._SY475_.jpg', 'upload/livros/678d57f3d9813pdf', '2025-01-19 16:52:19'),
(27, 'Vidas secas', 'Romance', 'Graciliano Ramos', 1938, 94, '000-000-000-025', 'Nacional', 'A história de uma família pobre da região seca do Nordeste e sua luta diária por trabalho e comida para sobreviver e superar as dificuldades do ambiente árido em que vive. Baseado no livro homônimo de Graciliano Ramos.', 0, 'https://www.record.com.br/wp-content/uploads/2019/07/16406.jpeg', 'upload/livros/678d584f70202pdf', '2025-01-19 16:53:51'),
(28, 'Percy Jackson e o ladrão de raios', 'Aventura', 'Rick Riordan', 2005, 200, '000-000-000-026', 'Internacional', 'O autor conjuga lendas da mitologia grega com aventuras no século XXI. Nelas, os deuses do Olimpo continuam vivos, ainda se apaixonam por mortais e geram filhos metade deuses, metade humanos, como os heróis da Grécia antiga. Marcados pelo destino, eles dificilmente passam da adolescência. Poucos conseguem descobrir sua identidade. O garoto-problema Percy Jackson é um deles. Tem experiências estranhas em que deuses e monstros mitológicos parecem saltar das páginas dos livros direto para a sua vida. Pior que isso: algumas dessas criaturas estão bastante irritadas. Um artefato precioso foi roubado do Monte Olimpo e Percy é o principal suspeito. Para restaurar a paz, ele e seus amigos – jovens heróis modernos – terão de fazer mais do que capturar o verdadeiro ladrão: precisam elucidar uma traição mais ameaçadora que fúria dos deuses.', 0, 'https://m.media-amazon.com/images/I/A1UjcPz4gZL._SL1500_.jpg', 'upload/livros/678d5890ba121pdf', '2025-01-19 16:54:56'),
(29, 'Percy Jackson e o mar de monstros', 'Aventura', 'Rick Riordan', 2006, 170, '000-000-000-027', 'Internacional', 'Nessa nova aventura, Percy e seus amigos estão em busca do Velocino de Ouro, único artefato mágico capaz de proteger da destruição seu lugar predileto e, até então, o mais seguro do mundo: o Acampamento Meio-Sangue. Com o envenenamento da árvore de Thalia por um inimigo misterioso, as fronteiras mágicas que protegem o Acampamento estão ameaçadas, e é preciso buscar o antídoto. Assim, nossos heróis partem em uma arriscada e incrível viagem pelo Mar de Monstros, localizado nas coordenadas 30-31-75-12: uma referência ao Triângulo das Bermudas. Lá, enfrentam seres fantásticos e muitos perigos e situações inusitadas, que põem à prova seu heroísmo e sua herança – quando Percy irá questionar se ser filho de Poseidon é uma honra ou uma terrível maldição. Combinando fatos contemporâneos com mitologia, fantasia com erudição, O Mar de Monstros diverte, encanta e ensina pais e filhos.', 0, 'https://m.media-amazon.com/images/I/A1rVWjvjcdL._SL1500_.jpg', 'upload/livros/678d58d6e0e80pdf', '2025-01-19 16:56:06'),
(30, 'Percy Jackson e a maldição do titã', 'Aventura', 'Rick Riordan', -2007, 162, '000-000-000-028', 'Internacional', 'Como sempre, Percy sabe que precisará contar com o poder de seus aliados heróis, com sua leal espada Contracorrente... e com uma caroninha da mãe. O que eles ainda não sabem é que os jovens descobertos não são os únicos em perigo: Cronos, o Senhor dos Titãs, arquitetou um de seus planos mais traiçoeiros, e nossos heróis serão presas fáceis. Um monstro ancestral foi despertado – um ser com poder suficiente para destruir o Olimpo –, e Ártemis, a única deusa capaz de encontrá-lo, desapareceu. Percy e seus amigos têm apenas uma semana para resgatar a deusa sequestrada e solucionar o mistério que ronda o monstro que ela caçava. Divertidíssima e repleta de ação, essa terceira aventura da série coloca nosso herói e seus aliados frente a frente com o maior desafio de suas vidas: a terrível profecia da maldição do titã.', 0, 'https://m.media-amazon.com/images/I/A1v41nm-PKL._SL1500_.jpg', 'upload/livros/678d59277bc5apdf', '2025-01-19 16:57:27'),
(31, 'Percy Jackson e a batalha do labirinto', 'Aventura', 'Rick Riordan', 2008, 140, '000-000-000-029', 'Internacional', 'O Monte Olimpo está em perigo. Cronos, o perverso titã que foi destronado e feito em pedaços pelos doze deuses olimpianos, prepara um retorno triunfal. O primeiro passo de suas tropas será atacar e destruir o campo de treinamento dos heróis, filhos de deuses com mortais, que desde a Grécia Antiga combatem na linha de frente em defesa dos olimpianos. Para assegurar que o refúgio de semideuses, o Acampamento Meio-Sangue, não seja invadido, Percy Jackson, Tyson, Annabeth e Grover são destacados para uma importante missão: deter as forças de Cronos antes que se aproximem do acampamento, no emaranhado de corredores do temido Labirinto de Dédalo – um interminável universo subterrâneo que, a cada curva, revela as mais aterrorizantes surpresas.', 0, 'https://m.media-amazon.com/images/I/A12XRUTsLbL._SL1500_.jpg', 'upload/livros/678d596308f89pdf', '2025-01-19 16:58:27'),
(32, 'Percy Jackson e o último olimpiano', 'Aventura', 'Rick Riordan', 2009, 140, '000-000-000-030', 'Internacional', 'Os meios-sangues passaram o ano inteiro preparando-se para a batalha contra os Titãs, e sabem que as chances de vitória são pequenas. O exército de Cronos está mais poderoso que nunca, e cada novo deus ou semideus que se une à causa confere mais força ao vingativo titã. Enquanto os Olimpianos se ocupam de conter a fúria do monstro Tifão, Cronos avança em direção à cidade de Nova York, onde o Monte Olimpo está precariamente vigiado. Agora, apenas Percy Jackson e seu exército de heróis podem deter o Senhor do Tempo. Nesse quinto e último livro da série, o combate se acirra e o mundo que conhecemos está prestes a ser destruído. O destino da civilização está nas mãos do semideus anunciado na antiga profecia, e Percy está perto de completar dezesseis anos – a dúvida é: o herói será ou não capaz de tomar a decisão correta?', 0, 'https://m.media-amazon.com/images/I/A1DnSBI+WPL._SL1500_.jpg', 'upload/livros/678d599b537b4pdf', '2025-01-19 16:59:23'),
(33, 'Tudo bem quando termina bem', 'Comédia', 'William Shakespeare', 1623, 170, '000-000-000-031', 'Internacional', 'Helena, a filha órfã de um médico famoso, é a ala da Condessa de Rousillon, e perdidamente apaixonada por seu filho, o Conde Bertram, que foi enviado para a corte do rei da França. Apesar de sua beleza e valor, Helena não tem esperança de atrair Bertram, já que ela é de nascimento baixo e ele é um nobre. No entanto, quando a palavra vem de que o Rei está doente, ela vai para Paris e, utilizando artes de seu pai, curas da doença. Em troca, ela recebe a mão de qualquer homem no campo, ela escolhe Bertram. Seu novo marido está chocado com o jogo, no entanto, e logo após seu casamento foge França, acompanhado apenas de um canalha chamado Parolles, para lutar no exército do Duque de Florença. Helena chega à cidade e descobre que seu marido está tentando seduzir a filha virginal de uma Viúva gentilmente. Com a conivência da filha, de nome Diana, ela inventa para enganar Bertram: ele dá seu anel de Diana como um símbolo de seu amor, e quando ele chega ao seu quarto à noite, Helena está na cama, e eles fazem amor sem ele percebendo que é ela. Ao mesmo tempo, dois senhores no exército expor. O Rei está de visita, e consente Bertram se casar com a filha de um senhor, velho fiel, chamado Lafew. No entanto, ele percebe um anel no dedo de Bertram, que anteriormente pertencia a Helena - que foi um presente do Rei depois que ela salvou sua vida. (Helena deu o anel para Diana, em Florença, e ela por sua vez, deu a ela teria de ser amante.) Bertram está em uma perda para explicar de onde veio, mas só então Diana e sua mãe parecem explicar as coisas - seguido por Helena, que informa ao marido que ambas as condições foram cumpridas. Castigados, consente Bertram para ser um bom marido para ela.', 0, 'https://m.media-amazon.com/images/I/71Ez-SH-q5L._SL1500_.jpg', 'upload/livros/678d6aac4b86apdf', '2025-01-19 17:05:49'),
(34, 'Trabalhos de amor perdidos', 'Comédia', 'William Shakespeare', 1598, 148, '000-000-000-032', 'Internacional', 'Ferdinando, rei de Navarra, e três lordes querem cultivar o espírito e o conhecimento. Decidem-se então a três anos de jejum, abstinência sexual, muito estudo e pouco sono: quem for flagrado com uma mulher será acusado de traição. Mas logo chegam a princesa da França e três damas de companhia, fazendo com que os homens se arrependam amargamente dos seus juramentos. Cartas são escritas e entregues ao destinatário errado, disfarces e máscaras roubam a cena nesta hilariante e atualíssima comédia de Shakespeare sobre a dificuldade de se manter a palavra. Escrito entre 1595 e 1596, trata-se de um trabalho da juventude do autor e um dos mais exuberantes e espirituosos dos seus textos.', 0, 'https://www.lpm.com.br/livros/Imagens/trabalhos_de_amor_perdidos_nova__9788525412386_g.jpg', 'upload/livros/678d6aff7065apdf', '2025-01-19 17:07:01'),
(35, 'Sonho de uma noite de verão', 'Comédia', 'William Shakespeare', 1600, 108, '000-000-000-033', 'Internacional', '“Na palavra ‘sonho’ há uma natural conotação de despojamento, incerteza; ‘sonho’ pode ser qualquer um, qualquer coisa (...)” – assim Harold Bloom esmiúça o título desta que é considerada a primeira obra-prima de Shakespeare, drama singular em sua produção. Nesta fábula, há uma variedade de temas e relações, onde folclore e mitologia aliados ao encadeamento mágico e trágico compõem um painel onírico jamais visto em nenhuma das obras do dramaturgo inglês. Essa polifonia talvez seja a grande virtude deste texto em que Shakespeare utiliza-se de uma fina e inteligente comicidade para deixar a reverência a deuses e reis de lado, apresentando tais seres veneráveis sob aspectos pouco solenes; seres cuja elevação resida mesmo em suas próprias insuficiências e imperfeições, reforçando o caráter essencialmente universalista da obra do bardo inglês.', 0, 'https://m.media-amazon.com/images/I/915rFCUXeiL._SL1500_.jpg', 'upload/livros/678d5baa43be3pdf', '2025-01-19 17:08:10'),
(36, 'Sonetos', 'Poesia', 'Luís de Camões', 1595, 62, '000-000-000-034', 'Nacional', 'Livro de poesias de Luís de Camões.', 0, 'https://m.media-amazon.com/images/I/51O9n2ggXEL._SL1050_.jpg', 'upload/livros/678d5be8a0a3apdf', '2025-01-19 17:09:12'),
(37, 'Senhora', 'Romance', 'José de Alencar', 1875, 255, '000-000-000-035', 'Nacional', 'História do casamento entre Aurélia, moça pobre e órfã que acaba se tornando herdeira de grande fortuna, e Fernando Seixas, frequentador dos altos círculos da corte, mas incapaz de manter financeiramente sua vida luxuosa. Apaixonada por Seixas em seus dias de pobreza, Aurélia é trocada pelo amado por uma moça com um dote de trinta contos de réis. Em uma das muitas reviravoltas do enredo, porém, Aurélia acaba herdeira de grande fortuna, e atrai Seixas de volta para si, anonimamente, em troca de uma quantia três vezes maior. No entanto, logo na noite de núpcias ela revela seu expediente e toda a hipocrisia inerente à transação da compra do marido, e a partir de então a relação dos recém-casados se torna um jogo mordaz de intrigas, manobras sigilosas e diálogos ácidos e repletos de subentendidos. Com sua narrativa concentrada na vida ociosa das classes abastadas e sua existência parasitária em torno da corte imperial, Senhora retrata um momento de transformação da sociedade brasileira, em que os valores patriarcais são cada vez mais deixados de lado em detrimento do poderio financeiro da burguesia ascendente e seu poder de influência na vida cotidiana, o que o torna ao mesmo tempo uma obra de arte representativa de um momento definidor da literatura brasileira e um documento precioso de uma transformação social que se mostraria irreversível.', 0, 'https://images.tcdn.com.br/img/img_prod/1323385/senhora_jose_de_alencar_principis_13711_1_b02b5a25d6c421143388a8d35da5cda0.jpg', 'upload/livros/678d5c262c1e1pdf', '2025-01-19 17:10:14'),
(38, 'Romeu e Julieta', 'Romance', 'William Shakespeare', 1597, 173, '000-000-000-036', 'Internacional', 'Romeu e Julieta é uma tragédia escrita nos primórdios da carreira literária de William Shakespeare, sobre dois adolescentes cuja morte acaba unindo suas famílias, outrora em pé de guerra.', 0, 'https://m.media-amazon.com/images/I/719trP22IcL._SL1360_.jpg', 'upload/livros/678d5c6892b14pdf', '2025-01-19 17:11:20'),
(39, 'Ricardo III', 'Tragédia', 'William Shakespeare', 1597, 91, '000-000-000-037', 'Internacional', 'O livro da peça retrata a ascensão ao trono de Ricardo, duque de Gloucester, um homem ambicioso, manipulador e impiedoso que usa de traições, assassinatos e mentiras para alcançar o poder. Apesar de sua crueldade, Ricardo III é um personagem carismático, cujo humor e astúcia conquistam o público. A obra aborda temas como ambição desmedida, corrupção e moralidade, culminando na queda trágica de Ricardo na Batalha de Bosworth. É uma das peças mais conhecidas de Shakespeare, famosa por sua complexidade psicológica e pelo monólogo icônico: \"Agora é o inverno do nosso descontentamento.\"', 0, 'https://m.media-amazon.com/images/I/81uiON7YuCL._SL1378_.jpg', 'upload/livros/678d5cad52cfbpdf', '2025-01-19 17:12:29'),
(40, 'Rei Lear', 'Tragédia', 'William Shakespeare', 1606, 194, '000-000-000-038', 'Internacional', 'A história segue o rei Lear, que decide dividir seu reino entre suas três filhas, Goneril, Regan e Cordélia, com base na demonstração de amor de cada uma por ele. Sua decisão precipitada, impulsionada pelo orgulho e cegueira emocional, resulta em traição, loucura e tragédia. O enredo explora temas de poder, lealdade, ingratidão e redenção, culminando em um desfecho profundamente trágico e reflexivo.', 0, 'https://cdl-static.s3-sa-east-1.amazonaws.com/covers/gg/9788582851111/rei-lear.jpg', 'upload/livros/678d5cf7ec6depdf', '2025-01-19 17:13:43'),
(41, 'Primeiro Fausto', 'Drama', 'Fernando Pessoa', 1986, 34, '000-000-000-039', 'Internacional', 'Trata-se de um poema dramático fragmentado, onde Pessoa explora os dilemas existenciais e metafísicos do ser humano. Inspirado pelo mito de Fausto, o texto reflete sobre a busca incessante pelo sentido da vida, a tensão entre a realidade e a idealização, e a angústia existencial. A obra é marcada por sua linguagem densa, filosófica e simbólica, sendo um testemunho da inquietação intelectual e espiritual do autor.', 0, 'https://m.media-amazon.com/images/I/81dUyuZqKPL._SL1500_.jpg', 'upload/livros/678d5d5d56df5pdf', '2025-01-19 17:15:25'),
(42, 'Poesias inéditas', 'Poesia', 'Fernando Pessoa', 1970, 52, '000-000-000-040', 'Internacional', 'Esta coletânea reúne poemas de Fernando Pessoa que não haviam sido publicados em vida. Os textos refletem a multiplicidade de temas e estilos característicos do autor, abordando desde questões filosóficas e existenciais até reflexões sobre a língua e a cultura portuguesa. A obra inclui poemas assinados pelo próprio Pessoa e por seus heterônimos, oferecendo uma visão mais completa do gênio literário que transcendeu fronteiras e épocas.', 0, 'https://m.media-amazon.com/images/I/61QXWuU+YWS._SL1500_.jpg', 'upload/livros/678d5da9ad8f6pdf', '2025-01-19 17:16:41'),
(43, 'Os sertões', 'Drama', 'Euclides da Cunha', 1902, 270, '000-000-000-041', 'Nacional', 'A obra é um relato detalhado da Guerra de Canudos, um conflito ocorrido no sertão da Bahia no final do século XIX. Dividido em três partes (\"A Terra\", \"O Homem\" e \"A Luta\"), o livro aborda aspectos geográficos, sociológicos e históricos da região e de seu povo. Euclides da Cunha combina observações científicas com uma análise literária profunda, criando um retrato crítico e grandioso da resistência liderada por Antônio Conselheiro. A obra é considerada um marco da literatura e da historiografia brasileiras.', 0, 'https://tse4.mm.bing.net/th?id=OIP.jLZLGXqcjxLIlofSo5D2MQHaLH&rs=1&pid=ImgDetMain', 'upload/livros/678d5e073bc01pdf', '2025-01-19 17:18:15'),
(44, 'A tragédia de Hamlet, o príncipe da Dinamarca', 'Tragédia', 'William Shakespeare', 1603, 116, '000-000-000-042', 'Internacional', 'O livro narra a história de Hamlet, príncipe da Dinamarca, que busca vingar o assassinato de seu pai, o rei, morto por seu tio Cláudio. Após o crime, Cláudio assume o trono e se casa com Gertrudes, mãe de Hamlet. A obra explora temas de traição, vingança, corrupção, loucura e mortalidade. Repleta de monólogos icônicos e dilemas filosóficos, \"Hamlet\" é considerada uma das maiores tragédias da literatura mundial.', 0, 'https://m.media-amazon.com/images/I/91AvfvzrKuL._SL1500_.jpg', 'upload/livros/678d5e5392fe2pdf', '2025-01-19 17:19:31'),
(45, 'MacBeth', 'Drama', 'William Shakespeare', 1623, 136, '000-000-000-043', 'Internacional', 'O livro narra a ascensão e queda de Macbeth, um general escocês que, encorajado por uma profecia de três bruxas e pela ambição de sua esposa, Lady Macbeth, assassina o rei Duncan para assumir o trono. Consumido pela culpa e paranoia, Macbeth se torna um tirano, levando à sua ruína e morte. A obra explora temas como ambição desmedida, moralidade, culpa e o destino, sendo uma das tragédias mais sombrias e célebres de Shakespeare.', 0, 'https://http2.mlstatic.com/D_NQ_NP_2X_911405-MLU53731117816_022023-F.webp', 'upload/livros/678d5ed37813cpdf', '2025-01-19 17:21:39'),
(46, 'O cortiço', 'Romance', 'Aluísio Azevedo', 1890, 118, '000-000-000-044', 'Nacional', 'O livro retrata a vida em um cortiço carioca, um ambiente coletivo habitado por pessoas de diferentes origens e histórias. A obra aborda temas como pobreza, exploração, relações sociais e preconceito, oferecendo um retrato crítico das condições de vida nas classes populares do Brasil no final do século XIX. Aluísio Azevedo utiliza o cortiço como metáfora para ilustrar o impacto do ambiente no comportamento humano, alinhando-se aos princípios do Naturalismo.', 0, 'https://m.media-amazon.com/images/I/81m1emiSp-S._SL1500_.jpg', 'upload/livros/678d5f35df441pdf', '2025-01-19 17:23:17'),
(47, 'A pianista', 'Conto', 'Machado de Assis', 1866, 20, '000-000-000-045', 'Nacional', 'O conto narra a história de uma jovem pianista chamada Malvina, que, ao se casar, vê-se presa às expectativas sociais e às limitações impostas pelo marido. A música, sua grande paixão e expressão de liberdade, passa a ser sufocada pelo ambiente opressor do casamento. Com maestria, Machado de Assis explora os dilemas da mulher na sociedade patriarcal do século XIX, abordando temas como arte, opressão e liberdade individual.', 0, 'https://m.media-amazon.com/images/I/61tlNNO6kRL._SL1050_.jpg', 'upload/livros/678d5fb5de2b0pdf', '2025-01-19 17:25:25'),
(48, 'A mulher de preto', 'Conto', 'Machado de Assis', 1870, 29, '000-000-000-046', 'Nacional', 'Neste conto, Machado de Assis apresenta um narrador que observa e reflete sobre a misteriosa figura de mulheres que usam vestidos pretos e frequentam um cemitério. A narrativa mistura lirismo e crítica social, explorando temas como o luto, a memória e os papéis atribuídos às mulheres na sociedade do século XIX. É uma obra que reflete a sensibilidade e a profundidade características do autor, revelando as sutilezas da vida cotidiana e os aspectos psicológicos das personagens.', 0, 'https://m.media-amazon.com/images/I/41b6E0pDLCL.jpg', 'upload/livros/678d6083b0b92pdf', '2025-01-19 17:28:51'),
(49, 'A metamorfose', 'Ficção Científica', 'Franz Kafka', 1915, 30, '000-000-000-047', 'Internacional', 'A história acompanha Gregor Samsa, um caixeiro-viajante que, ao acordar certa manhã, descobre que se transformou em um inseto monstruoso. Preso em um corpo estranho, ele enfrenta o afastamento de sua família e a degradação de sua condição física e emocional. A obra explora temas como alienação, responsabilidade familiar e o absurdo da existência, sendo considerada um dos grandes clássicos da literatura mundial.', 0, 'https://m.media-amazon.com/images/I/71QLwli7GUL._SL1500_.jpg', 'upload/livros/678d60e7eb6f4pdf', '2025-01-19 17:30:31'),
(50, 'As primaveras', 'Poesia', 'Casimiro de Abreu', 1859, 94, '000-000-000-048', 'Nacional', 'Esta coletânea de poesias é marcada pela sensibilidade romântica e pelo tom nostálgico característico de Casimiro de Abreu. Os poemas abordam temas como a saudade da infância, o amor idealizado, a ligação com a natureza e a melancolia. \"As Primaveras\" consagrou o autor como uma das principais vozes da segunda geração do romantismo no Brasil, destacando-se pela simplicidade e pela musicalidade de seus versos.', 0, 'https://m.media-amazon.com/images/I/71M+gr7oFeL._SL1500_.jpg', 'upload/livros/678d615bb051fpdf', '2025-01-19 17:32:27'),
(51, 'Os maias', 'Romance', 'José Maria Eça de Queiroz', 1888, 288, '000-000-000-049', 'Nacional', 'A obra narra a história da família Maia, com foco em Carlos da Maia e seu avô Afonso. Situado na sociedade lisboeta do século XIX, o romance explora temas como decadência social, hipocrisia, amores impossíveis e conflitos familiares. A trama principal gira em torno do romance entre Carlos e Maria Eduarda, que culmina em uma descoberta trágica. Considerado um dos maiores romances da língua portuguesa, \"Os Maias\" é uma crítica mordaz e detalhada da sociedade portuguesa da época.', 0, 'https://m.media-amazon.com/images/I/816Lq8xxPlL._SL1500_.jpg', 'upload/livros/678d61a35d9e4pdf', '2025-01-19 17:33:39'),
(52, 'A cartomante', 'Conto', 'Machado de Assis', 1884, 7, '000-000-000-050', 'Nacional', 'O conto narra a história de um triângulo amoroso entre Vilela, sua esposa Rita e seu amigo Camilo. Em um momento de dúvida sobre seu relacionamento extraconjugal com Camilo, Rita consulta uma cartomante, que lhe dá previsões reconfortantes. Camilo, inicialmente cético, também acaba recorrendo à cartomante devido à desconfiança de Vilela. O desfecho é surpreendente e trágico, demonstrando a ironia e o talento de Machado de Assis em explorar a psicologia dos personagens e o destino irônico.', 0, 'https://m.media-amazon.com/images/I/913JKLHKN1L._SL1500_.jpg', 'upload/livros/678d61f51583dpdf', '2025-01-19 17:35:01'),
(53, 'A tempestade', 'Drama', 'William Shakespeare', 1611, 68, '000-000-000-051', 'Internacional', 'A peça conta a história de Próspero, o duque de Milão deposto, que vive exilado em uma ilha remota com sua filha Miranda. Próspero, um poderoso mago, usa suas habilidades mágicas e o espírito Ariel para invocar uma tempestade que faz naufragar um navio com seus inimigos. À medida que os sobreviventes chegam à ilha, intrigas, vingança e reconciliações se desenrolam. A obra explora temas de poder, traição, perdão e a conexão entre humanidade e magia, sendo considerada uma das últimas peças de Shakespeare.', 0, 'https://m.media-amazon.com/images/I/91IRKga3qTL._SL1500_.jpg', 'upload/livros/678d630366647pdf', '2025-01-19 17:39:31'),
(54, 'Diário de bitita', 'Biografia', 'Carolina Maria de Jesus', 1982, 186, '000-000-000-052', 'Nacional', 'A dura luta cotidiana de uma família negra, nas primeiras décadas do século passado, narrada do ponto de vista de uma menina inteligente e interessada. O Diário de Bitita documenta seus esforços para, ainda criança, encontrar trabalho, garantir a sobrevivência material e manter a dignidade, acima de tudo. Um painel da sociedade agrária brasileira, realçado com tintas de injustiça social, preconceito e discriminação. A autora, Carolina Maria de Jesus, foi protagonista de um fenômeno editorial no país, nos anos 1960.', 0, 'https://m.media-amazon.com/images/I/612dfTY2TbL._SL1453_.jpg', 'upload/livros/678d63d8a0666pdf', '2025-01-19 17:43:04'),
(55, 'Quarto de despejo', 'Biografia', 'Carolina Maria de Jesus', 1960, 176, '000-000-000-053', 'Nacional', 'O diário da catadora de papel Carolina Maria de Jesus deu origem a este livro, que relata o cotidiano triste e cruel da vida na favela. A linguagem simples, mas contundente, comove o leitor pelo realismo e pelo olhar sensível na hora de contar o que viu, viveu e sentiu nos anos em que morou na comunidade do Canindé, em São Paulo, com três filhos.', 0, 'https://m.media-amazon.com/images/I/71z42zpEwbL._SL1500_.jpg', 'upload/livros/678d6412d37bapdf', '2025-01-19 17:44:02'),
(56, 'Pedaços da fome', 'Romance', 'Carolina Maria de Jesus', 1963, 109, '000-000-000-054', 'Nacional', 'Pedaços da Fome é um romance ficcional escrito por Carolina Maria de Jesus, que aborda fome e miséria na cidade de São Paulo a partir de experiências vivenciadas pela própria autora. Foi publicado em 1963, pela editora Aquila, sendo uma das cinco obras que a escritora brasileira publicou ainda em vida.', 0, 'https://wikifavelas.com.br/images/3/34/Capa_Peda%C3%A7os_da_Fome..jpg', 'upload/livros/678d6656a89a1pdf', '2025-01-19 17:53:42'),
(57, 'Provérbios', 'Poesia', 'Carolina Maria de Jesus', 1963, 30, '000-000-000-056', 'Nacional', 'O livro Provérbios foi lançado no mesmo ano em que saiu Pedaços da fome, 1963, e também de forma independente. Trata-se de uma obra que condensa uma marca estética importante na escrita de Carolina, justamente a palavra proverbial, que pode ser recolhida em sua produção de forma geral.  O provérbio é uma forma literária muito presente nas culturas africanas, demarca um conhecimento condensado em poucas palavras; articula, no discurso, pílulas de encantamento.', 0, 'https://carolinamariadejesus.ims.com.br/wp-content/uploads/2024/02/52.png', 'upload/livros/678d676a3ef50pdf', '2025-01-19 17:58:18'),
(58, 'Antologia pessoal', 'Poesia', 'Carolina Maria de Jesus', 1996, 122, '000-000-000-057', 'Nacional', 'Em 1996 a editora da UFRJ lançou uma antologia de poemas reunindo parte da produção poética de Carolina Maria de Jesus.', 0, 'https://carolinamariadejesus.ims.com.br/wp-content/uploads/2024/02/53.png', 'upload/livros/678d67ff162e0pdf', '2025-01-19 18:00:47'),
(59, 'Orgulho e preconceito', 'Romance', 'Jane Austen', 1813, 547, '000-000-000-058', 'Internacional', 'Orgulho e preconceito é o livro mais famoso de Jane Austen e possui uma série de personagens inesquecíveis e um enredo memorável. Austen nos apresenta Elizabeth Bennet como heroína irresistível e seu pretendente aristocrático, o sr. Darcy. Nesse livro, aspectos diferentes são abordados: orgulho encontra preconceito, ascendência social confronta desprezo social, equívocos e julgamentos antecipados conduzem alguns personagens ao sofrimento e ao escândalo. O livro pode ser considerado a obra-prima da escritora, que equilibra comédia com seriedade, observação meticulosa das atitudes humanas e sua ironia refinada. A nova coleção possui capa dura e estilo inspirado nos bullet journals.', 0, 'https://m.media-amazon.com/images/I/719esIW3D7L._SL1297_.jpg', 'upload/livros/678d6867e72c6pdf', '2025-01-19 18:02:31'),
(60, 'Persuasão', 'Romance', 'Jane Austen', 1817, 199, '000-000-000-059', 'Internacional', '\"Persuasão” foi o último trabalho completo de Jane Austen. O livro conta a história de Anne Elliot, uma das heroínas mais tranquilas e reservadas de Austen, mas, ao mesmo tempo, uma das mais fortes e abertas às mudanças. O livro enaltece a constância do amor numa época turbulenta na história da Inglaterra: as guerras napoleônicas. Escrito nesse período, o romance descreve como uma mulher pode permanecer fiel ao seu passado e, ainda assim, pensar em um futuro feliz. Austen expõe de maneira sutil como uma mulher pode passar por cima das convenções sociais e das restrições femininas em busca da felicidade.', 0, 'https://m.media-amazon.com/images/I/814Y0DO2OZL._SL1297_.jpg', 'upload/livros/678d68c527457pdf', '2025-01-19 18:04:05'),
(61, 'Emma', 'Romance', 'Jane Austen', 1815, 727, '000-000-000-060', 'Internacional', 'Ao comentar sobre Emma Woodhouse, Jane Austen brincou com seus leitores ao dizer que Emma é o tipo de \"heroína que ninguém além dela própria iria gostar muito\". Entretanto, ela é irresistível, dona de uma personalidade singular e capaz de despertar no leitor o amor e ódio ao mesmo tempo. Emma é profunda, talvez por isso seja a única personagem dos seis livros publicados de Austen, cujo próprio nome é também o título da obra. O livro é um ótimo exemplo de sagacidade e ironia, típicos da escrita de Jane Austen, e é considerado por muitos seu romance mais elaborado. A habilidade que a escritora teve em demonstrar os diversos aspectos da natureza humana de forma bastante realista e afetuosa eleva esta obra a uma sátira brilhante.', 0, 'https://m.media-amazon.com/images/I/71bLpWzzrtL._SL1297_.jpg', 'upload/livros/678d6940bbd5apdf', '2025-01-19 18:06:08'),
(62, 'Razão e sensibilidade', 'Romance', 'Jane Austen', 1811, 552, '000-000-000-061', 'Internacional', '\"Razão e Sensibilidade\" é um livro em que as irmãs Elinor e Marianne representam uma dualidade, de maneira alternada, ao longo da narrativa. As expectativas vividas pelas duas com a perda, o amor e a esperança, nos aponta para um excelente panorama da vida das mulheres de sua época. As irmãs vivem em uma sociedade rígida, e ambas tentam sobreviver a esse mundo cheio de regras e injustiças. Tanto a sensível e sensata Elinor como a romântica e impetuosa Marianne se veem fadadas a aceitar um destino infeliz por não possuírem fortuna nem influências, obrigadas a viver em um mundo dominado por dinheiro e interesse. As duas personagens passam por um processo intenso de aprendizagem, mesclando a razão com os sentimentos em busca por um final feliz.', 0, 'https://m.media-amazon.com/images/I/81eN74IRg4L._SL1297_.jpg', 'upload/livros/678d699eb3d3apdf', '2025-01-19 18:07:42'),
(63, 'Lady Susan', 'Romance', 'Jane Austen', 1871, 133, '000-000-000-062', 'Internacional', 'Lady Susan, o romance epistolar de Jane Austen, nunca recebeu muita atenção dos leitores em comparação com os seus outros seis romances maiores, principalmente por ser uma obra curta. Os estudiosos de sua obra estimam que tenha sido escrito entre os anos de 1793 e 1794, quando a jovem escritora encontrava-se em seus últimos anos de adolescência e representa um hiato na totalidade da obra de Jane Austen por se caracterizar como um estudo sobre uma mulher adulta, que usa sua inteligência e charme para manipular, trair e abusar de suas vítimas, sejam elas, amantes, amigos ou os membros de sua própria família. A história de LADY SUSAN gira em torno de sua personagem principal, a bela e coquete Lady Susan Vernon (uma das melhores personagens criadas por Jane Austen, em tudo diferente às protagonistas de seus romances posteriores), uma viúva na casa de seus 30 anos, que busca um novo e vantajoso matrimônio para si, ao mesmo tempo em que tenta arranjar um casamento para sua filha com um homem rico e tolo que esta úl', 0, 'https://livrariapublica.com.br/capa/lady-susan-e-outras-historias-jane-austen-pdf-B085FXL6HM.webp', 'upload/livros/678d6a1864c9epdf', '2025-01-19 18:09:44');

-- --------------------------------------------------------

--
-- Estrutura para tabela `usuarios`
--

CREATE TABLE `usuarios` (
  `id` int(11) NOT NULL,
  `nomedeusuario` varchar(20) NOT NULL,
  `nome` varchar(100) NOT NULL,
  `dataNasc` date NOT NULL,
  `email` varchar(100) NOT NULL,
  `senha` varchar(255) NOT NULL,
  `data_cadastro` datetime NOT NULL DEFAULT current_timestamp(),
  `foto_path` varchar(500) NOT NULL,
  `livros_lidos` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `usuarios`
--

INSERT INTO `usuarios` (`id`, `nomedeusuario`, `nome`, `dataNasc`, `email`, `senha`, `data_cadastro`, `foto_path`, `livros_lidos`) VALUES
(1, 'mariii', 'Mariana', '2008-08-04', 'marianalima@email.com', '840da3dfcc610a1b97764f9e95299c6f', '2025-01-19 11:32:02', './images/profile picture.jpg', 0),
(2, 'vargas.rita', 'Maria Rita', '2007-12-13', 'mariarita@email.com', 'f29b38f160f87ae86df31cee1982066f', '2025-01-19 11:46:05', './images/profile picture.jpg', 1),
(3, 'mallumauro', 'Maria Luiza', '2010-02-22', 'malluvargas@email.com', 'd7a84628c025d30f7b2c52c958767e76', '2025-01-19 11:46:51', 'upload/usuarios/678d109d6f6adpng', 0),
(5, 'annabia', 'Anna Beatriz', '0000-00-00', 'annabeatriz@email.com', '02ebef8c56a7ada3f1ed5e900e3143c0', '2025-01-19 14:35:57', './images/profile picture.jpg', 0);

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `leitura`
--
ALTER TABLE `leitura`
  ADD PRIMARY KEY (`idLivro`,`idUsuario`),
  ADD KEY `idUsuario` (`idUsuario`);

--
-- Índices de tabela `livro`
--
ALTER TABLE `livro`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `nome` (`nome`);

--
-- Índices de tabela `usuarios`
--
ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `nomedeusuario` (`nomedeusuario`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `livro`
--
ALTER TABLE `livro`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=64;

--
-- AUTO_INCREMENT de tabela `usuarios`
--
ALTER TABLE `usuarios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- Restrições para tabelas despejadas
--

--
-- Restrições para tabelas `leitura`
--
ALTER TABLE `leitura`
  ADD CONSTRAINT `leitura_ibfk_1` FOREIGN KEY (`idLivro`) REFERENCES `livro` (`id`),
  ADD CONSTRAINT `leitura_ibfk_2` FOREIGN KEY (`idUsuario`) REFERENCES `usuarios` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
